### ISSUE TITLE
Old/Unreadable Data with Jenkins 2.60.1 and plugin > 1.25

### ISSUE THREAD

**Issue by cmichallek** [jenkinsci/tikal-multijob-plugin#116]
Hi,

since the last plugin upgrade to 1.25 we get some old/unreadable data for every job we run.
Data looks like this:

```
ConversionException: Could not call com.tikal.jenkins.plugins.multijob.MultiJobParametersAction.readResolve() : null : Could not call com.tikal.jenkins.plugins.multijob.MultiJobParametersAction.readResolve() : null ---- Debugging information ---- message : Could not call com.tikal.jenkins.plugins.multijob.MultiJobParametersAction.readResolve() : null cause-exception : com.thoughtworks.xstream.converters.reflection.ObjectAccessException cause-message : Could not call com.tikal.jenkins.plugins.multijob.MultiJobParametersAction.readResolve() : null class : com.tikal.jenkins.plugins.multijob.MultiJobParametersAction required-type : com.tikal.jenkins.plugins.multijob.MultiJobParametersAction converter-type : hudson.util.RobustReflectionConverter path : /build/actions/com.tikal.jenkins.plugins.multijob.MultiJobParametersAction line number : 23 -------------------------------


ConversionException: Could not call com.tikal.jenkins.plugins.multijob.MultiJobParametersAction.readResolve() : null : Could not call com.tikal.jenkins.plugins.multijob.MultiJobParametersAction.readResolve() : null ---- Debugging information ---- message : Could not call com.tikal.jenkins.plugins.multijob.MultiJobParametersAction.readResolve() : null cause-exception : com.thoughtworks.xstream.converters.reflection.ObjectAccessException cause-message : Could not call com.tikal.jenkins.plugins.multijob.MultiJobParametersAction.readResolve() : null class : com.tikal.jenkins.plugins.multijob.MultiJobParametersAction required-type : com.tikal.jenkins.plugins.multijob.MultiJobParametersAction converter-type : hudson.util.RobustReflectionConverter path : /com.tikal.jenkins.plugins.multijob.MultiJobBuild/subBuilds/com.tikal.jenkins.plugins.multijob.MultiJobBuild$SubBuild/build/actions/com.tikal.jenkins.plugins.multijob.MultiJobParametersAction line number : 662 -------------------------------, ConversionException: Could not call com.tikal.jenkins.plugins.multijob.MultiJobParametersAction.readResolve() : null : Could not call com.tikal.jenkins.plugins.multijob.MultiJobParametersAction.readResolve() : null ---- Debugging information ---- message : Could not call com.tikal.jenkins.plugins.multijob.MultiJobParametersAction.readResolve() : null cause-exception : com.thoughtworks.xstream.converters.reflection.ObjectAccessException cause-message : Could not call com.tikal.jenkins.plugins.multijob.MultiJobParametersAction.readResolve() : null class : com.tikal.jenkins.plugins.multijob.MultiJobParametersAction required-type : com.tikal.jenkins.plugins.multijob.MultiJobParametersAction converter-type : hudson.util.RobustReflectionConverter path : /com.tikal.jenkins.plugins.multijob.MultiJobBuild/subBuilds/com.tikal.jenkins.plugins.multijob.MultiJobBuild$SubBuild[2]/build/actions/com.tikal.jenkins.plugins.multijob.MultiJobParametersAction line number : 1622 -------------------------------, ConversionException: Could not call com.tikal.jenkins.plugins.multijob.MultiJobParametersAction.readResolve() : null : Could not call com.tikal.jenkins.plugins.multijob.MultiJobParametersAction.readResolve() : null ---- Debugging information ---- message : Could not call com.tikal.jenkins.plugins.multijob.MultiJobParametersAction.readResolve() : null cause-exception : com.thoughtworks.xstream.converters.reflection.ObjectAccessException cause-message : Could not call com.tikal.jenkins.plugins.multijob.MultiJobParametersAction.readResolve() : null class : com.tikal.jenkins.plugins.multijob.MultiJobParametersAction required-type : com.tikal.jenkins.plugins.multijob.MultiJobParametersAction converter-type : hudson.util.RobustReflectionConverter path : /com.tikal.jenkins.plugins.multijob.MultiJobBuild/subBuilds/com.tikal.jenkins.plugins.multijob.MultiJobBuild$SubBuild[3]/build/actions/com.tikal.jenkins.plugins.multijob.MultiJobParametersAction line number : 1723 -------------------------------, ConversionException: Could not call com.tikal.jenkins.plugins.multijob.MultiJobParametersAction.readResolve() : null : Could not call com.tikal.jenkins.plugins.multijob.MultiJobParametersAction.readResolve() : null ---- Debugging information ---- message : Could not call com.tikal.jenkins.plugins.multijob.MultiJobParametersAction.readResolve() : null cause-exception : com.thoughtworks.xstream.converters.reflection.ObjectAccessException cause-message : Could not call com.tikal.jenkins.plugins.multijob.MultiJobParametersAction.readResolve() : null class : com.tikal.jenkins.plugins.multijob.MultiJobParametersAction required-type : com.tikal.jenkins.plugins.multijob.MultiJobParametersAction converter-type : hudson.util.RobustReflectionConverter path : /com.tikal.jenkins.plugins.multijob.MultiJobBuild/subBuilds/com.tikal.jenkins.plugins.multijob.MultiJobBuild$SubBuild[4]/build/actions/com.tikal.jenkins.plugins.multijob.MultiJobParametersAction line number : 1786 -------------------------------
```

1.26 didnt solve this problem, but it doesnt impact the jobs so far. Plugin still works and does its job.
But its a bit annoying.

Any ideas how to fix this?

greetings

Christian

**Comment by aswild** [comment]
*bump*

I have the same issue on my installation with Jenkins 2.67. If I update the Multijob plugin past 1.24, I get unreadable data errors and lose the parameters on all the old Multijob builds.

**Comment by cohencil** [comment]
Released 1.28 in an attempt to fix this. If issue still occur please elaborate some more on your use case and recreation steps.

**Comment by aswild** [comment]
Updated multijob to 1.28 and don't have the unreadable data issues and I can access old builds' parameters. (still on Jenkins 2.67).

Thanks for the fix!

**Comment by vyepishov** [comment]
Hi all,

We have following multiple lines with messages about unreadable data (after upgrade of Jenkins from 2.60.3 to 2.121.1 and multijob plugin to 1.30):
MissingFieldException: No field 'build' found in class 'com.tikal.jenkins.plugins.multijob.MultiJobBuild$SubBuild'
Thanks for the help in advance.

Best Regards,
Vadym

**Comment by abienkowski** [comment]
Looks like it was fixed in 1.28, however, it back in 1.32
